# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_subscription_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscription_active',
            field=models.BooleanField(default=True),
        ),
    ]
